# Generated by Django 5.0.6 on 2024-07-04 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_transaction_sheet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='transaction_sheet',
            field=models.FileField(upload_to='sheets', validators=[django.core.validators.FileExtensionValidator(['csv', 'pdf'])]),
        ),
    ]
