# Generated by Django 5.0.6 on 2024-07-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_transaction_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
