# Generated by Django 5.1.4 on 2025-09-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
