# Generated by Django 5.1.4 on 2025-09-28 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='transaction_sheet',
            field=models.FileField(blank=True, null=True, upload_to='sheets', validators=[django.core.validators.FileExtensionValidator(['csv'])]),
        ),
    ]
