# Generated by Django 5.0.6 on 2024-07-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_remove_budget_end_date_remove_budget_start_date'),
        ('budgets', '0006_auto_categories'),
    ]

    operations = [
    ]
