# Generated by Django 5.0.6 on 2024-07-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0007_merge_20240704_1148'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rule',
            unique_together={('keyword', 'ruleset')},
        ),
    ]
