# Generated by Django 5.0.6 on 2024-07-09 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('budgets', '0008_alter_rule_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-title']},
        ),
        migrations.AlterField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruleset', to='accounts.user'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('title',)},
        ),
    ]
