# Generated by Django 5.0.6 on 2024-07-09 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0008_alter_rule_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title']},
        ),
    ]
