# Generated by Django 5.1.3 on 2024-12-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0009_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcategory',
            name='is_earning',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
