# Generated by Django 5.1.3 on 2024-12-23 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0010_budgetcategory_is_earning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('final_projected_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('final_projected_date', models.DateField(null=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('created_dt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savingstracker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectedBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('projected_date', models.DateField(null=True)),
                ('report_id', models.IntegerField()),
                ('savings_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectedbalance', to='budgets.savingstracker')),
            ],
        ),
    ]
