# Generated by Django 5.1.4 on 2025-09-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0012_alter_savingstracker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
